name: Run linters
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Go dependencies for vulnerabilities
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.27
      - name: Run Go linter
        uses: sonatype-nexus-community/nancy-github-action@1.0.0

